# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=password

# Expose the PostgreSQL port
EXPOSE 5432

# Default command to run PostgreSQL
CMD ["postgres"]
